#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# run_jobs_local.sh — Run all jobs locally using parallel processes
###############################################################################
#
# This is the LOCAL equivalent of AWS Batch. Instead of submitting to the
# cloud, it runs all jobs on your machine using xargs for parallelism.
# Useful for testing the pipeline before cloud submission.
#
# Usage:
#   cloud_runs/run_jobs_local.sh JOBS_JSON GRAPH_PKL OUTPUT_DIR [PARALLELISM] [EXTRA_ARGS...]
#
# Arguments:
#   JOBS_JSON       Path to jobs.json file (generated by generate_jobs.py)
#   GRAPH_PKL       Path to network graph pickle file
#   OUTPUT_DIR      Directory for output files (created if needed)
#   PARALLELISM     Number of parallel processes (default: 4)
#   EXTRA_ARGS      Additional args passed to run_job.py (e.g. --shots 1024)
#
# Example:
#   cloud_runs/run_jobs_local.sh cloud_runs/jobs.json \
#     networkgraphs/2x3_grid_network_graph.pkl ./out 8 \
#     --shots 4096 --optimization-level 1
#
# Each process runs one (code, path) job sequentially. With PARALLELISM=8,
# 8 jobs run simultaneously. Total time ≈ (num_jobs / parallelism) × time_per_job.
###############################################################################

if [[ $# -lt 3 ]]; then
  echo "Usage: $0 JOBS_JSON GRAPH_PKL OUTPUT_DIR [PARALLELISM] [EXTRA_ARGS...]" >&2
  exit 1
fi

JOBS_FILE="$1"
GRAPH_PKL="$2"
OUTPUT_DIR="$3"

if [[ $# -ge 4 ]]; then
  PARALLELISM="$4"
  shift 4
else
  PARALLELISM=4
  shift 3
fi

# Count total jobs in the file
NUM_JOBS=$(python - "$JOBS_FILE" <<'PY'
import json, sys
with open(sys.argv[1], 'r', encoding='utf-8') as f:
    data = json.load(f)
if isinstance(data, dict):
    jobs = data.get('jobs', [])
else:
    jobs = data
print(len(jobs))
PY
)

if [[ "${NUM_JOBS}" -le 0 ]]; then
  echo "No jobs found in ${JOBS_FILE}" >&2
  exit 1
fi

# Force single-threaded execution per process to avoid CPU contention.
# Each xargs worker should use exactly 1 core.
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1

# Generate job indices (0 to N-1) and run them in parallel.
# xargs -P controls parallelism, -n1 passes one index per invocation,
# -I{} substitutes the index into the command.
seq 0 $((NUM_JOBS - 1)) | xargs -n1 -P "${PARALLELISM}" -I{} \
  python cloud_runs/run_job.py \
    --jobs-file "${JOBS_FILE}" \
    --job-index {} \
    --graph "${GRAPH_PKL}" \
    --output-dir "${OUTPUT_DIR}" \
    "$@"

wait
